config/routes.rb
Rails.application.routes.draw do
  resources :administrators
  resources :products
  resources :categories
  namespace :admin do
    resources :administrators
    resources :products
    resources :categorie
  end    
  
    resource :user_sessions, :only => [:create, :new, :destroy]
    
    

    root 'home#index'

end

app/models/administrator.rb
class Administrator < ActiveRecord::Base
  validates_presence_of :email, :name, :password
  validates_confirmation_of :password
  has_secure_password
    
    
    def self.authenticate(email, password)
            find_by_email(email).
            try(:authenticate, password)
    end
end

app/controllers/admin/administrators_controller.rb
class Admin::AdministratorsController < ApplicationController
    before_filter :require_authentication  
    before_action :set_administrator, only: [:show, :edit, :update, :destroy]
   

  # GET /administrators
  # GET /administrators.json
  def index
    @administrators = Administrator.all
  end

  # GET /administrators/1
  # GET /administrators/1.json
  def show
  end

  # GET /administrators/new
  def new
    @administrator = Administrator.new
  end

  # GET /administrators/1/edit
  def edit
  end

  # POST /administrators
  # POST /administrators.json
  def create
    @administrator = Administrator.new(administrator_params)

    respond_to do |format|
      if @administrator.save
          format.html { redirect_to [:admin, @administrator], notice: 'Administrator was successfully created.' }
        format.json { render :show, status: :created, location: @administrator }
      else
        format.html { render :new }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /administrators/1
  # PATCH/PUT /administrators/1.json
  def update
    respond_to do |format|
      if @administrator.update(administrator_params)
        format.html { redirect_to [:admin, @administrator], notice: 'Administrator was successfully updated.' }
        format.json { render :show, status: :ok, location: @administrator }
      else
        format.html { render :edit }
        format.json { render json: @administrator.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /administrators/1
  # DELETE /administrators/1.json
  def destroy
    @administrator.destroy
    respond_to do |format|
      format.html { redirect_to admin_administrators_url, notice: 'Administrator was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_administrator
      @administrator = Administrator.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def administrator_params
      params.require(:administrator).permit(:name, :email, :password)
    end
end

app/helpers/administrators_helper.rb
module AdministratorsHelper
end

app/views/admin/administrators/_form.html.erb
<%= form_for([:admin, @administrator]) do |f| %>
  <% if @administrator.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@administrator.errors.count, "error") %> prohibited this administrator from being saved:</h2>

      <ul>
      <% @administrator.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div>
    <%= f.label :password_confirmation %> <br>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/administrators/edit.html.erb
<h1>Editing Administrator</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @administrator] %> |
<%= link_to 'Back', admin_administrators_path %>

app/views/admin/administrators/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Administrators</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @administrators.each do |administrator| %>
      <tr>
        <td><%= administrator.name %></td>
        <td><%= administrator.email %></td>
        <td><%= link_to 'Show', [:admin, administrator] %></td>
          <td><%= link_to 'Edit', edit_admin_administrator_path(administrator) %></td>
        <td><%= link_to 'Destroy', [:admin, administrator], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Administrator', new_admin_administrator_path %>

app/views/admin/administrators/new.html.erb
<h1>New Administrator</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_administrators_path %>

app/views/admin/administrators/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @administrator.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @administrator.email %>
</p>

<p>
  <strong>Password:</strong>
  <%= @administrator.password %>
</p>

<%= link_to 'Edit', edit_admin_administrator_path(@administrator) %> |
<%= link_to 'Back', admin_administrators_path %>