config/routes.rb
Rails.application.routes.draw do
  resources :administrators
  resources :products
  resources :categories
  namespace :admin do
    resources :administrators
    resources :products
    resources :categorie
  end    
  
    resource :user_sessions, :only => [:create, :new, :destroy]
    
    

    root 'home#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
    belongs_to :category
    
    mount_uploader :image, PhotoUploader
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
    before_filter :require_authentication
    before_action :set_product, only: [:show, :edit, :update, :destroy]
  
  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
          format.html { redirect_to [:admin, @product], notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to [:admin, @product], notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
        format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :image, :description, :category_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end
    
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :image, :description, :category_id)
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/admin/products/_form.html.erb
<%= form_for([:admin, @product]) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :image %><br>
    <%= f.file_field :image %>
  </div>
  
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  
   <div class="field">
    <%= f.label :price %><br>
    <%= f.text_field :price %>
  </div>
   
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description %>
  </div>
  
  <div class="field">
    <%= f.label :category_id %><br>
    <%= f.text_field :category_id %>
  </div>
  
  <div>
      <%= f.collection_select(:category_id, Category.order(:name), :id, :name, :prompt => "Selecione uma categoria") %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>  
<% end %>

app/views/admin/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin, @product] %> |
<%= link_to 'Back', admin_products_path %>

app/views/admin/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Products</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Price</th>
      <th>Image</th>
      <th>Description</th>
      <th>Category</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.name %></td>
        <td><%= product.price %></td>
        <td><img src="<%= product.image %>" alt=""></td>
        <td><%= product.description %></td>
        <td><%= product.category.name %></td>
          <td><%= link_to 'Show', [:admin, product] %></td>
          <td><%= link_to 'Edit', edit_admin_product_path(product) %></td>
        <td><%= link_to 'Destroy', [:admin, product], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_admin_product_path %>

app/views/admin/products/new.html.erb
<h1>New Product</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_products_path %>

app/views/admin/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Image:</strong>
  <%= @product.image %>
</p>

<p>
  <strong>Description:</strong>
  <%= @product.description %>
</p>

<p>
  <strong>Category:</strong>
    <%= @product.category.name %>
</p>

<%= link_to 'Edit', edit_admin_product_path(@product) %> |
<%= link_to 'Back', admin_products_path %>